name: Sentiment Generator

on:
  schedule:
    - cron: '*/10 11-23 * * *'   # a cada 10 min entre 11h e 23h UTC
  workflow_dispatch: {}

jobs:
  run-sentiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Run sentiment generator
        run: python -m src.classifiers.sentiment_macro --batch-size 200 --once
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
